package com.ad364.drl_rulebc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Customer implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Loyalty Level")
	private java.lang.String loyaltyLevel;
	@org.kie.api.definition.type.Label("Age")
	private java.lang.Integer age;
	@org.kie.api.definition.type.Label(value = "Skip Exit Rows?")
	private java.lang.Boolean skipExitRows;

	public Customer() {
	}

	public java.lang.String getLoyaltyLevel() {
		return this.loyaltyLevel;
	}

	public void setLoyaltyLevel(java.lang.String loyaltyLevel) {
		this.loyaltyLevel = loyaltyLevel;
	}

	public java.lang.Integer getAge() {
		return this.age;
	}

	public void setAge(java.lang.Integer age) {
		this.age = age;
	}

	public java.lang.Boolean getSkipExitRows() {
		return this.skipExitRows;
	}

	public void setSkipExitRows(java.lang.Boolean skipExitRows) {
		this.skipExitRows = skipExitRows;
	}

	public Customer(java.lang.String loyaltyLevel, java.lang.Integer age,
			java.lang.Boolean skipExitRows) {
		this.loyaltyLevel = loyaltyLevel;
		this.age = age;
		this.skipExitRows = skipExitRows;
	}

}