package com.ad364.drl_rulebc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class TicketRequest implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Seating Class")
	private java.lang.String seatClass;

	public TicketRequest() {
	}

	public java.lang.String getSeatClass() {
		return this.seatClass;
	}

	public void setSeatClass(java.lang.String seatClass) {
		this.seatClass = seatClass;
	}

	public TicketRequest(java.lang.String seatClass) {
		this.seatClass = seatClass;
	}

}